# Generated by Django 5.2.8 on 2026-06-02 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='min_participantes',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='evento',
            name='status',
            field=models.CharField(choices=[('PLANNING', 'Planejamento'), ('WAITING', 'Aguardando Jogadores'), ('ONGOING', 'Em Andamento'), ('CLOSED', 'Encerrado')], default='PLANNING', max_length=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MensagemChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='core.evento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpcaoVotacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LOCAL', 'Local'), ('DATA', 'Data/Hora')], max_length=10)),
                ('valor', models.CharField(max_length=200)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes_voto', to='core.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ORGANIZER', 'Organizador'), ('PLAYER', 'Jogador')], default='PLAYER', max_length=20)),
                ('status', models.CharField(choices=[('INTERESTED', 'Interessado'), ('CONFIRMED', 'Confirmado')], default='INTERESTED', max_length=20)),
                ('pontos_acumulados', models.IntegerField(default=0)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='core.evento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('evento', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Rodada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('encerrada', models.BooleanField(default=False)),
                ('aprovada_por_todos', models.BooleanField(default=False)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rodadas', to='core.evento')),
            ],
        ),
        migrations.CreateModel(
            name='PropostaPontuacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos_ganhos', models.IntegerField()),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.participante')),
                ('rodada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='core.rodada')),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='core.opcaovotacao')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('opcao', 'user')},
            },
        ),
        migrations.CreateModel(
            name='VotoRodada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concorda', models.BooleanField(default=True)),
                ('rodada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_validacao', to='core.rodada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('rodada', 'user')},
            },
        ),
    ]
