# Generated by Django 6.0 on 2026-06-30 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_evento_min_participantes_evento_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rodada',
            name='aprovada_por_todos',
        ),
        migrations.RemoveField(
            model_name='rodada',
            name='encerrada',
        ),
        migrations.AddField(
            model_name='propostapontuacao',
            name='proposto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propostas_feitas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rodada',
            name='status',
            field=models.CharField(choices=[('PONTUACAO', 'Aguardando Pontuação'), ('VOTACAO', 'Em Votação'), ('CONTESTADA', 'Contestada'), ('APROVADA', 'Aprovada')], default='PONTUACAO', max_length=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='emoji',
            field=models.CharField(choices=[('🃏', 'Cartas'), ('♟️', 'Tabuleiro'), ('🐉', 'RPG'), ('🏸', 'Esportes'), ('🎸', 'Música')], default='🃏', max_length=10),
        ),
        migrations.AlterField(
            model_name='evento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mensagemchat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='opcaovotacao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='propostapontuacao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rodada',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='votorodada',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='propostapontuacao',
            unique_together={('rodada', 'participante')},
        ),
    ]
